pub mod init;
pub mod chat;
pub mod status;
pub mod config;
pub mod serve;
#[cfg(feature = "knowledge")]
pub mod knowledge;
pub mod vision;
#[cfg(feature = "audio")]
pub mod audio;
#[cfg(feature = "scripting")]
pub mod script;
#[cfg(feature = "web")]
pub mod web;
pub mod skill;
#[cfg(feature = "web")]
pub mod gateway;
pub mod research;
pub mod debug;
pub mod audit;
pub mod analyze;
